create table my_order(
    id                  number(10)          generated by default on null as identity(start with 10000000 nocache)
    ,table_number       number(4)
    ,customer_name      varchar2(128)
    ,customer_address   varchar2(256)
    ,status_id          number(2)
    ,created            timestamp
    ,created_by         varchar2(62)
    ,updated            timestamp
    ,updated_by         varchar2(62)
);

alter table my_order
add constraint pk_my_order
primary key (id);

alter table my_order
add constraint fk_my_order1
foreign key (status_id) references my_order_status(id);

comment on table my_order is 
'All orders and customer details';

comment on column my_order.id           is 'This is a sequence generated order number (eight digit)';
comment on column my_order.table_number is 'Table number of the resturant, ideally to be denormalised to separate table';
comment on column my_order.table_number is 'customer name, deally to be denormalised to separate table';
comment on column my_order.table_number is 'customer address, ideally to be denormalised to separate table';
comment on column my_order.created      is 'Datetimestamp when order is created';
comment on column my_order.created_by   is 'Username who created the order';
comment on column my_order.updated      is 'Datetimestamp when order is last updated';
comment on column my_order.updated_by   is 'Username who updated the order';

