create table my_order_status(
    id                  number(2)          generated by default on null as identity(start with 1 nocache)
    ,status             varchar2(30)
    ,description        varchar2(4000)
    ,created            timestamp
    ,created_by         varchar2(62)
    ,updated            timestamp
    ,updated_by         varchar2(62)
);

alter table my_order_status
add constraint pk_my_order_status
primary key (id);

alter table my_order_status
add constraint uk_my_order_status1
unique(status);

comment on table my_order_status is 
'contains alllowable order statuses';

comment on column my_order_status.id          is 'This is a sequence generated primary key';
comment on column my_order_status.description is 'Overall description of the status';
comment on column my_order_status.created     is 'Datetimestamp when status is created';
comment on column my_order_status.created_by  is 'Username who created the order status';
comment on column my_order_status.updated     is 'Datetimestamp when order status is last updated';
comment on column my_order_status.updated_by  is 'Username who updated the order status';

insert into my_order_status(status, description)
values ('NEW', 'New');

insert into my_order_status(status, description)
values ('BEP', 'Being Prepared');

insert into my_order_status(status, description)
values ('DEL', 'Delivered/Served');

insert into my_order_status(status, description)
values ('CAN', 'Cancelled');

insert into my_order_status(status, description)
values ('COM', 'Completed');