create table my_order_item(
    id                  number          generated by default on null as identity(start with 1 nocache)
    ,order_id           number(10)
    ,item_id            number(4)
    ,quantity           number(2)
    ,created            timestamp
    ,created_by         varchar2(62)
    ,updated            timestamp
    ,updated_by         varchar2(62)
);

alter table my_order_item
add constraint pk_my_order_item
primary key (id);

alter table my_order_item
add constraint uk_my_order_item1
unique (order_id, item_id);

alter table my_order_item
add constraint fk_my_order_item1
foreign key (order_id) references my_order(id);

alter table my_order_item
add constraint fk_my_order_item2
foreign key (item_id) references my_item(id);

comment on table my_order_item is 
'Line items of orders';

comment on column my_order_item.id            is 'This is a sequence generated number';
comment on column my_order_item.order_id      is 'Order id of the order';
comment on column my_order_item.item_id       is 'item ID from item table';
comment on column my_order_item.quantity      is 'Quantity';
comment on column my_order_item.created       is 'Datetimestamp when event is created';
comment on column my_order_item.created_by    is 'Username who created the event';
comment on column my_order_item.updated       is 'Datetimestamp when order is last updated';
comment on column my_order_item.updated_by    is 'Username who updated the order';

