CREATE TABLE TCKT_FILE_DATA
(
Extract_Batch_Number                       char(6)
,Extract_Date                              char(8)
,Request_Type                              char(1)
,Reference_Key                             char(8)
,Company_Code                              char(1)
,Department_Code                           char(3)
,Style_Code                                char(8)
,Colour_Code                               char(5)
,Colour_Desc                               char(15)
,Invoice_Supplier_indi                     char(1)
,Reason_Code                               char(2)
,UK_Size                                   char(10)
,European_Size                             char(10)
,Bartag_Quantity                           char(8)
,Barcode                                   char(13)
,Supplier_Number                           char(10)
,Delivery_Name                             char(40)
,Delivery_Address_ln_1                     char(40)
,Delivery_Address_ln_2                     char(40)
,Delivery_Address_ln_3                     char(40)
,Delivery_Address_ln_4                     char(40)
,Delivery_Address_ln_5                     char(40)
,Delivery_Address_ln_6                     char(10)
,Priority_Indicator                        char(2)
,Tag_Type                                  char(2)
,Additional_Tag_Type                       char(2)
,UV_filter                                 char(2)
,End_use_description                       char(15)
,Footwear_ref                              char(20)
,Country_of_Origin                         char(20)
,Foreign_Currency_Code_1                   char(3)
,Foreign_Currency_Code_2                   char(3)
,Foreign_Currency_Code_3                   char(3)
,Foreign_Currency_Code_4                   char(3)
,UK_Retail_Price                           char(10)
,Foreign_Prices_1                          char(11)
,Foreign_Prices_2                          char(11)
,Foreign_Prices_3                          char(11)
,Foreign_Prices_4                          char(11)
,Composition_name_1                        char(20)
,Composition_Percentage_1                  char(4)
,Composition_name_2                        char(20)
,Composition_Percentage_2                  char(4)
,Composition_name_3                        char(20)
,Composition_Percentage_3                  char(4)
,Composition_name_4                        char(20)
,Composition_Percentage_4                  char(4)
,Composition_name_5                        char(20)
,Composition_Percentage_5                  char(4)
,Composition_name_6                        char(20)
,Composition_Percentage_6                  char(4)
,Composition_name_7                        char(20)
,Composition_Percentage_7                  char(4)
,Composition_name_8                        char(20)
,Composition_Percentage_8                  char(4)
,Composition_name_9                        char(20)
,Composition_Percentage_9                  char(4)
,Composition_name_10                       char(20)
,Composition_Percentage_10                 char(4)
,Supplier_Name                             char(40)
,Invoice_Name                              char(40)
,Invoice_Address_line_1                    char(40)
,Invoice_Address_line_2                    char(40)
,Invoice_Address_line_3                    char(40)
,Invoice_Address_line_4                    char(40)
,Invoice_Address_line_5                    char(40)
,Invoice_Address_line_6                    char(10)
,Blank_Spaces                              char(9)
,Multi_pack_quantity                       char(5)
,Sku_id                                    char(15)
,US_Size                                   char(10)
)
ORGANIZATION EXTERNAL
(
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY S_PDF_DIR
    ACCESS PARAMETERS
    (
        RECORDS DELIMITED BY NEWLINE
        BADFILE     'S_PDF_DIR':'TCKT_FILE_DATA.bad'
        DISCARDFILE 'S_PDF_DIR':'TCKT_FILE_DATA.dsc'
        LOGFILE     'S_PDF_DIR':'TCKT_FILE_DATA.log'
        FIELDS
        (
            Extract_Batch_Number        position(1:6)                     char(6)
            ,Extract_Date               position(7:14)                    char(8)
            ,Request_Type               position(15:15)                   char(1)
            ,Reference_Key              position(16:23)                   char(8)
            ,Company_Code               position(24:24)                   char(1)
            ,Department_Code            position(25:27)                   char(3)
            ,Style_Code                 position(28:35)                   char(8)
            ,Colour_Code                position(36:40)                   char(5)
            ,Colour_Desc                position(41:55)                   char(15)
            ,Invoice_Supplier_indi      position(56:56)                   char(1)
            ,Reason_Code                position(57:58)                   char(2)
            ,UK_Size                    position(59:68)                   char(10)
            ,European_Size              position(69:78)                   char(10)
            ,Bartag_Quantity            position(79:86)                   char(8)
            ,Barcode                    position(87:99)                   char(13)
            ,Supplier_Number            position(100:109)                 char(10)
            ,Delivery_Name              position(110:149)                 char(40)
            ,Delivery_Address_ln_1      position(150:189)                 char(40)
            ,Delivery_Address_ln_2      position(190:229)                 char(40)
            ,Delivery_Address_ln_3      position(230:269)                 char(40)
            ,Delivery_Address_ln_4      position(270:309)                 char(40)
            ,Delivery_Address_ln_5      position(310:349)                 char(40)
            ,Delivery_Address_ln_6      position(350:359)                 char(10)
            ,Priority_Indicator         position(360:361)                 char(2)
            ,Tag_Type                   position(362:363)                 char(2)
            ,Additional_Tag_Type        position(364:365)                 char(2)
            ,UV_filter                  position(366:367)                 char(2)
            ,End_use_description        position(368:382)                 char(15)
            ,Footwear_ref               position(383:402)                 char(20)
            ,Country_of_Origin          position(403:422)                 char(20)
            ,Foreign_Currency_Code_1    position(423:425)                 char(3)
            ,Foreign_Currency_Code_2    position(426:428)                 char(3)
            ,Foreign_Currency_Code_3    position(429:431)                 char(3)
            ,Foreign_Currency_Code_4    position(432:434)                 char(3)
            ,UK_Retail_Price            position(435:444)                 char(10)
            ,Foreign_Prices_1           position(445:455)                 char(11)
            ,Foreign_Prices_2           position(456:466)                 char(11)
            ,Foreign_Prices_3           position(467:477)                 char(11)
            ,Foreign_Prices_4           position(478:488)                 char(11)
            ,Composition_name_1         position(489:508)                 char(20)
            ,Composition_Percentage_1   position(509:512)                 char(4)
            ,Composition_name_2         position(513:532)                 char(20)
            ,Composition_Percentage_2   position(533:536)                 char(4)
            ,Composition_name_3         position(537:556)                 char(20)
            ,Composition_Percentage_3   position(557:560)                 char(4)
            ,Composition_name_4         position(561:580)                 char(20)
            ,Composition_Percentage_4   position(581:584)                 char(4)
            ,Composition_name_5         position(585:604)                 char(20)
            ,Composition_Percentage_5   position(605:608)                 char(4)
            ,Composition_name_6         position(609:628)                 char(20)
            ,Composition_Percentage_6   position(629:632)                 char(4)
            ,Composition_name_7         position(633:652)                 char(20)
            ,Composition_Percentage_7   position(653:656)                 char(4)
            ,Composition_name_8         position(657:676)                 char(20)
            ,Composition_Percentage_8   position(677:680)                 char(4)
            ,Composition_name_9         position(681:700)                 char(20)
            ,Composition_Percentage_9   position(701:704)                 char(4)
            ,Composition_name_10        position(705:724)                 char(20)
            ,Composition_Percentage_10  position(725:728)                 char(4)
            ,Supplier_Name              position(729:768)                 char(40)
            ,Invoice_Name               position(769:808)                 char(40)
            ,Invoice_Address_line_1     position(809:848)                 char(40)
            ,Invoice_Address_line_2     position(849:888)                 char(40)
            ,Invoice_Address_line_3     position(889:928)                 char(40)
            ,Invoice_Address_line_4     position(929:968)                 char(40)
            ,Invoice_Address_line_5     position(969:1008)                char(40)
            ,Invoice_Address_line_6     position(1009:1018)               char(10)
            ,Blank_Spaces               position(1019:1027)               char(9)
            ,Multi_pack_quantity        position(1028:1032)               char(5)
            ,Sku_id                     position(1033:1047)               char(15)
            ,US_Size                    position(1048:1057)               char(10)
        )
    )
        LOCATION ('byw888tckt160928697.dat')
)
  REJECT LIMIT UNLIMITED
/